### ISSUE TITLE
"Less secure app access" setting is no longer in use.

### ISSUE THREAD

**Issue by dapoadedire** [sukanya-pai/Django-Email-Sender#13]
![image](https://user-images.githubusercontent.com/95668340/176266318-365429c2-a924-491a-884e-100bd85480a6.png)

**Comment by sukanya-pai** [comment]
Without making this setting, is it working for you? Looks like Google has removed this setting recently on June 2nd.

**Comment by dapoadedire** [comment]
No.

**Comment by sukanya-pai** [comment]
Updated the steps to make use of Google App Password in README, please follow that. Also, ensure you check the change.log file to see what has changed :)
