### ISSUE TITLE
Page not found(404)

### ISSUE THREAD

**Issue by pratikkabade** [sukanya-pai/Django-Email-Sender#15]
### screenshot of error

![image](https://user-images.githubusercontent.com/76637730/185787438-ec58ac7b-7a3c-40db-b03b-8575930ff857.png)

**Comment by sukanya-pai** [comment]
What is the URL link that you are using? Please refer to this[this](https://github.com/sukanya-pai/Django-Email-Sender/blob/aa548c461394b304502b816d06a82f57ae4f6606/change.log#L10)  line from change.log file.

**Comment by pratikkabade** [comment]
Yes, [This](http://127.0.0.1:8000/api/send-mail) link works
 
I opened the default link from terminal the one shown in the screenshot.
