### ISSUE TITLE
Google doesn't allow App Password anymore

### ISSUE THREAD

**Issue by town-idiot** [sukanya-pai/Django-Email-Sender#19]
Heya, just wanting to update that Google now doesn't allow app password anymore, is there any workaround with this? Thanks!

**Comment by 1-Rishabh-Jain-1** [comment]
It allows app passwords. I am currently using it.

**Comment by ivemzy** [comment]
app password works fine, its gmail password that doesnt work

**Comment by ofmukesh** [comment]
> Heya, just wanting to update that Google now doesn't allow app password anymore, is there any workaround with this? Thanks!

**No, google allows app password,** may be u have tried gmail password or other ,, Please read the [Readme.md]() and try again
